version: '3'
services:
    # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
    jhipster-elasticsearch7:
        build: jhipster-elasticsearch/
        ports:
            - "10200:10200"
        # Uncomment this section to have elasticsearch data loaded from a volume
        #volumes:
        #   - ./log-data:/usr/share/elasticsearch/data
    jhipster-logstash7:
        build: jhipster-logstash/
        environment:
            - INPUT_TCP_PORT=6000
            - INPUT_UDP_PORT=6000
            - INPUT_HTTP_PORT=6001
            - ELASTICSEARCH_HOST=jhipster-elasticsearch
            - ELASTICSEARCH_PORT=10200
            - LOGSTASH_DEBUG=true
        ports:
            - "6000:6000"
            - "6001:6001"
            - "10600:10600"
        depends_on:
            - jhipster-elasticsearch7

    jhipster-console7:
        build: jhipster-console/
        environment:
            - ELASTICSEARCH_URL=http://jhipster-elasticsearch:10200
        ports:
            - "6601:6601"
        depends_on:
            - jhipster-elasticsearch7

    jhipster-import-dashboards7:
        build: jhipster-import-dashboards/
        environment:
            - ELASTICSEARCH_URL=http://jhipster-elasticsearch:10200
        depends_on:
            - jhipster-elasticsearch7

    jhipster-alerter7:
        build: jhipster-alerter/
        environment:
            - WEBHOOK_URL=https://
        volumes:
            - ./jhipster-alerter/config.yaml:/opt/elastalert/config.yaml
            - ./alerts/rules/:/opt/elastalert/rules

    #https://www.elastic.co/guide/en/elasticsearch/client/curator/current/configuration.html
    jhipster-curator7:
        build: jhipster-curator/
        environment:
            - ES_HOST=jhipster-elasticsearch
            - UNIT_COUNT=7
            - UNIT=days

    jhipster-zipkin7:
        build: jhipster-zipkin/
        environment:
            - ES_HOSTS=http://jhipster-elasticsearch:10200
            - ES_INDEX=traces
            - ZIPKIN_UI_LOGS_URL=http://localhost:6601/app/kibana#/discover/d0682f20-e0e9-11e7-9c68-0b9a0f0c183c?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-30d,mode:quick,to:now))&_a=(columns:!(X-B3-TraceId,app_name,level,message),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'logs-*',key:X-B3-TraceId,negate:!f,params:(query:'trace',type:phrase),type:phrase,value:'trace'),query:(match:(X-B3-TraceId:(query:'{traceId}',type:phrase))))),index:'logs-*',interval:auto,query:(language:lucene,query:''),sort:!('@timestamp',desc))
        ports:
            - 10411:10411